### ISSUE TITLE
Swallows unrelated errors

### ISSUE THREAD

**Issue by necolas** [davidtheclark/postcss-log-warnings#6]
This plugin is swallowing webpack errors when included in the postcss loader. It prints:

```
** postcss-log-warnings: warnings were found **
```

and swallows the JS error (unrelated to css processing)

**Comment by davidtheclark** [comment]
Can you please try either master or v0.2.2 that I just released? I think the changes should probably stop this problem but want to make sure it works in your particular situation.

**Comment by davidtheclark** [comment]
Make that 0.2.3. I made a lot of dumb mistakes trying to get that published ... very tired today I guess.

**Comment by necolas** [comment]
Same problem. Screenshot of the output resulting from a JS parse error once this plugin is enabled.

![](http://i.imgur.com/lnuCJ2q.png)

**Comment by davidtheclark** [comment]
I was seeing that, too -- must have made changes that only fixed certain situations. That's annoying. I will setup something with webpack to try to reproduce and take care of this within the next couple of days.

**Comment by davidtheclark** [comment]
Ok ... I think I learned about my stupid decisions and fixed the problem. Now the plugin should throw a regular error if `throwError: true` instead of trying to exit the process; and the runner -- in this case the webpack loader -- should know what to do with the error. I made some test branches for using this with gulp and webpack and I was able to reproduce the kind of error you were hitting, and this new change fixed it. I hope that's that.

So @necolas, please try v0.3.0 on your code and see if it works for you. Thanks!

**Comment by necolas** [comment]
Looks like 0.3.0 works. Thanks!

**Comment by davidtheclark** [comment]
Ah, good.
